// Write a Java program to input week number(1-7) and print day of weekname using switch case.

import java.util.*;

public class WeekDays {
    public static void main(String args[]) {
        Scanner sc=new Scanner(System.in);
        System.out.print("Enter week number(1-7): ");
        int week = sc.nextInt();

        switch(week) {
            case 1: 
                System.out.println("Monday");
                break;
            case 2:
                System.out.println("Tuesday");
                break;
            case 3:
                System.out.println("Wednedday");
                break;
            case 4:
                System.out.println("Thursday");
                break;
            case 5:
                System.out.println("Friday");
                break;
            case 6:
                System.out.println("Saturday");
                break;
            case 7:
                System.out.println("Sunday");
                break;
            default:
                System.out.println("Invalid input! Please enter week number between (1-7).");
        }
    }
}